### ISSUE TITLE
[Bug] Bullet points are buggy when there are less than 3 companies

### ISSUE THREAD

**Issue by laniehei** [temporalio/temporaldotio#57]
### Describe the bug

As you scroll down the usecases page, the bullet points where companies are typically listed show even if there are no companies, and they show half-way when they're behind other items. See screenshots provided. 

### To Reproduce

Scroll down through https://temporal.io/usecases

### Expected behavior

As I scroll, I expect the bullet points not to show if they're supposed to be hidden/there are no companies listed

### Screenshots/Terminal output

![Screen Shot 2021-11-24 at 9 51 07 AM](https://user-images.githubusercontent.com/13442634/143290397-de47d7b2-b74c-43be-94f0-aa3700a41e34.png)
![Screen Shot 2021-11-24 at 9 51 15 AM](https://user-images.githubusercontent.com/13442634/143290402-6f327280-9cdb-49af-871e-91defeb72ec4.png)

### Versions

chrome

**Comment by sw-yx** [comment]
fixed
